### PR TITLE
Prepare for jQuery removal

### PR DESCRIPTION
**Pull request by andysellick**
## What / why

- we're going to be removing jQuery from GOV.UK
- jQuery currently comes from the components gem, included via `static` for applications
- `licence-finder` has a load of jQuery in `application.js` that is complicated to remove and has no associated tests
- therefore I'm proposing that we give `licence-finder` its own jQuery, which can be upgraded or removed later without blocking the rest of GOV.UK
- this has involved the addition of a `package.json` to manage the dependency

This approach is currently a proposal. An alternative could be:

- write some tests for the JS/jQuery
- convert it to not using jQuery

...but currently this would be very complicated and time consuming, not only because this jQuery uses AJAX but also because my local version of licence-finder doesn't work properly anyway (before making any of these changes).

## Visual changes
None.

### CODE REVIEW

**Comment by andysellick** [comment]
@alex-ju @kevindew I've tagged you for review on this even though it's a draft so you can sanity check my approach. Happy to discuss alternatives.

**Comment by kevindew** [comment]
Thanks @andysellick, certainly a thorny app jQuery wise.

In regards to:

> it has to be included in the application template like this because of the way rails //= require mechanism works - which adds each script into the head using a defer, meaning that jquery.min.js doesn't load fast enough to be available to application.js

is that a reference to the load ordering?  As I was under the impression that setting multiple scripts with defer attribute means they are executed in the order they are defined in the document.

I did some quick experiments and I think Slimmer might have a bug with scripts with a defer attribute and be inverting the ordering (I understand what it's doing is moving each script with a defer attribute to the top of the head element, this will mean that it inverts the order by putting each new script element it finds at the top of head: https://github.com/alphagov/slimmer/commit/9f818656c0a748c5496e9e66286ff5ba809c2fae)

Examples:

<details>
<summary>Without Slimmer</summary>

```
<script src="/assets/licencefinder/vendor/jquery.min.self-693ce4426a47c40b80ac9cd618fbd633c4182bff664d1f25009813f456c3ed12.js?body=1" defer="defer"></script>
<script src="/assets/licencefinder/govuk_publishing_components/vendor/polyfills/closest.self-3ff4acf0f76b53aa2af6164ead57f7b6c74491446fdfcf9770c74a2ab31303bc.js?body=1" defer="defer"></script>
<script src="/assets/licencefinder/govuk_publishing_components/vendor/polyfills/common.self-e7c50a5ef995541a77fece86095a2e178ff0b258072d5102b2a22c428faaa151.js?body=1" defer="defer"></script>
<script src="/assets/licencefinder/govuk_publishing_components/vendor/polyfills/indexOf.self-55b186cecc92d7aad81b32958442593f417ff6ba23e47b5933921ce930772b09.js?body=1" defer="defer"></script>
<script src="/assets/licencefinder/govuk_publishing_components/vendor/polyfills/all.self-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855.js?body=1" defer="defer"></script>
<script src="/assets/licencefinder/govuk_publishing_components/lib/cookie-functions.self-12b657bfb9d4cab1d2e3e2d22f27d30a1ffe65eabc707718a96c03e53150b199.js?body=1" defer="defer"></script>
<script src="/assets/licencefinder/govuk_publishing_components/lib/current-location.self-e77bab80576e9d3e3ec87e53de86246d9ac7f3bc2f73de6f84cfa23914d0ec38.js?body=1" defer="defer"></script>
<script src="/assets/licencefinder/govuk_publishing_components/lib/extend-object.self-e5a492402a7948173e61143c574ab91c27b977290fb5a5c285835fa75f23e329.js?body=1" defer="defer"></script>
<script src="/assets/licencefinder/govuk/vendor/polyfills/Element/prototype/classList.self-24ea6b4d70ff944d2a3ea3b2addc6dc65e7207e61b0613231fbdf109bf33c65b.js?body=1" defer="defer"></script>
<script src="/assets/licencefinder/govuk_publishing_components/lib/govspeak/magna-charta.self-be88c1eb30fa3873342442e93e79eca8074e19b13cdf7efd6b1601f101ee1395.js?body=1" defer="defer"></script>
<script src="/assets/licencefinder/govuk_publishing_components/lib/govspeak/barchart-enhancement.self-e25027187ed5f9496be080ef806ed6885524fcdd0fc11a5493d7cb992dd65ce8.js?body=1" defer="defer"></script>
<script src="/assets/licencefinder/govuk_publishing_components/lib/govspeak/youtube-link-enhancement.self-e8e0f96c2a6e4ae79e013efd3df1f640b8fbbe20f3c69471a326fff7b220a434.js?body=1" defer="defer"></script>
<script src="/assets/licencefinder/govuk_publishing_components/lib/govspeak/all.self-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855.js?body=1" defer="defer"></script>
<script src="/assets/licencefinder/govuk_publishing_components/lib/header-navigation.self-a32d2122448971c701aed4f9645e3e4b822c8832edc6ea54600dc5dc336c9175.js?body=1" defer="defer"></script>
<script src="/assets/licencefinder/govuk_publishing_components/lib/initial-focus.self-5616b95226332c73fe9c275943f9bf3dee1dc1a9253f5424c1f228f1e085f21b.js?body=1" defer="defer"></script>
<script src="/assets/licencefinder/govuk_publishing_components/lib/primary-links.self-d4316ed5c90a29e5ef75727161b830527cbbc1205316ebbdc2159f8a78b8ad3b.js?body=1" defer="defer"></script>
<script src="/assets/licencefinder/govuk_publishing_components/lib/toggle-input-class-on-focus.self-b414e5d0852199d271ce8c6e6096a3291a4633a44e458e59ceadbe867d48564f.js?body=1" defer="defer"></script>
<script src="/assets/licencefinder/govuk_publishing_components/lib/toggle.self-38338210dcb686548b38719c605312f86a08ea129e9f06b5ceb6dc5fd79835e4.js?body=1" defer="defer"></script>
<script src="/assets/licencefinder/govuk_publishing_components/lib/trigger-event.self-ac2703aeeac13c7393d50c1f78f22c1f420f2587c03459b6939df352bcbfa6ce.js?body=1" defer="defer"></script>
<script src="/assets/licencefinder/govuk_publishing_components/lib.self-75a11da44c802486bc6f65640aa48a730f0f684c5c07a42ba3cd1735eb3fb070.js?body=1" defer="defer"></script>
<script src="/assets/licencefinder/govuk/components/button/button.self-89d5c839a849e187a5ee60a15247d196c649b92349c85bcfb14f314302a3c8e0.js?body=1" defer="defer"></script>
<script src="/assets/licencefinder/govuk_publishing_components/components/button.self-ad1fee7b83325a3c8501424581d5da1d39e001c1e06752bf6cf2f4f57d416f17.js?body=1" defer="defer"></script>
<script src="/assets/licencefinder/govuk_publishing_components/components/feedback.self-8483b07ed7688e9d74489ac502796580548b8f8eba12dccd04ce7a45fb3ffe23.js?body=1" defer="defer"></script>
<script src="/assets/licencefinder/application.self-273be21e76cf3fad26a91eace2cf0e0adf848148523edea04027d7692a5b34b8.js?body=1" defer="defer"></script>
```
</details>

<details>
<summary>With Slimmer</summary>

```
<script src="/assets/licencefinder/application.self-273be21e76cf3fad26a91eace2cf0e0adf848148523edea04027d7692a5b34b8.js?body=1" defer></script>
<script src="/assets/licencefinder/govuk_publishing_components/components/feedback.self-8483b07ed7688e9d74489ac502796580548b8f8eba12dccd04ce7a45fb3ffe23.js?body=1" defer></script>
<script src="/assets/licencefinder/govuk_publishing_components/components/button.self-ad1fee7b83325a3c8501424581d5da1d39e001c1e06752bf6cf2f4f57d416f17.js?body=1" defer></script>
<script src="/assets/licencefinder/govuk/components/button/button.self-89d5c839a849e187a5ee60a15247d196c649b92349c85bcfb14f314302a3c8e0.js?body=1" defer></script>
<script src="/assets/licencefinder/govuk_publishing_components/lib.self-75a11da44c802486bc6f65640aa48a730f0f684c5c07a42ba3cd1735eb3fb070.js?body=1" defer></script>
<script src="/assets/licencefinder/govuk_publishing_components/lib/trigger-event.self-ac2703aeeac13c7393d50c1f78f22c1f420f2587c03459b6939df352bcbfa6ce.js?body=1" defer></script>
<script src="/assets/licencefinder/govuk_publishing_components/lib/toggle.self-38338210dcb686548b38719c605312f86a08ea129e9f06b5ceb6dc5fd79835e4.js?body=1" defer></script>
<script src="/assets/licencefinder/govuk_publishing_components/lib/toggle-input-class-on-focus.self-b414e5d0852199d271ce8c6e6096a3291a4633a44e458e59ceadbe867d48564f.js?body=1" defer></script>
<script src="/assets/licencefinder/govuk_publishing_components/lib/primary-links.self-d4316ed5c90a29e5ef75727161b830527cbbc1205316ebbdc2159f8a78b8ad3b.js?body=1" defer></script>
<script src="/assets/licencefinder/govuk_publishing_components/lib/initial-focus.self-5616b95226332c73fe9c275943f9bf3dee1dc1a9253f5424c1f228f1e085f21b.js?body=1" defer></script>
<script src="/assets/licencefinder/govuk_publishing_components/lib/header-navigation.self-a32d2122448971c701aed4f9645e3e4b822c8832edc6ea54600dc5dc336c9175.js?body=1" defer></script>
<script src="/assets/licencefinder/govuk_publishing_components/lib/govspeak/all.self-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855.js?body=1" defer></script>
<script src="/assets/licencefinder/govuk_publishing_components/lib/govspeak/youtube-link-enhancement.self-e8e0f96c2a6e4ae79e013efd3df1f640b8fbbe20f3c69471a326fff7b220a434.js?body=1" defer></script>
<script src="/assets/licencefinder/govuk_publishing_components/lib/govspeak/barchart-enhancement.self-e25027187ed5f9496be080ef806ed6885524fcdd0fc11a5493d7cb992dd65ce8.js?body=1" defer></script>
<script src="/assets/licencefinder/govuk_publishing_components/lib/govspeak/magna-charta.self-be88c1eb30fa3873342442e93e79eca8074e19b13cdf7efd6b1601f101ee1395.js?body=1" defer></script>
<script src="/assets/licencefinder/govuk/vendor/polyfills/Element/prototype/classList.self-24ea6b4d70ff944d2a3ea3b2addc6dc65e7207e61b0613231fbdf109bf33c65b.js?body=1" defer></script>
<script src="/assets/licencefinder/govuk_publishing_components/lib/extend-object.self-e5a492402a7948173e61143c574ab91c27b977290fb5a5c285835fa75f23e329.js?body=1" defer></script>
<script src="/assets/licencefinder/govuk_publishing_components/lib/current-location.self-e77bab80576e9d3e3ec87e53de86246d9ac7f3bc2f73de6f84cfa23914d0ec38.js?body=1" defer></script>
<script src="/assets/licencefinder/govuk_publishing_components/lib/cookie-functions.self-12b657bfb9d4cab1d2e3e2d22f27d30a1ffe65eabc707718a96c03e53150b199.js?body=1" defer></script>
<script src="/assets/licencefinder/govuk_publishing_components/vendor/polyfills/all.self-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855.js?body=1" defer></script>
<script src="/assets/licencefinder/govuk_publishing_components/vendor/polyfills/indexOf.self-55b186cecc92d7aad81b32958442593f417ff6ba23e47b5933921ce930772b09.js?body=1" defer></script>
<script src="/assets/licencefinder/govuk_publishing_components/vendor/polyfills/common.self-e7c50a5ef995541a77fece86095a2e178ff0b258072d5102b2a22c428faaa151.js?body=1" defer></script>
<script src="/assets/licencefinder/govuk_publishing_components/vendor/polyfills/closest.self-3ff4acf0f76b53aa2af6164ead57f7b6c74491446fdfcf9770c74a2ab31303bc.js?body=1" defer></script>
<script src="/assets/licencefinder/vendor/jquery.min.self-693ce4426a47c40b80ac9cd618fbd633c4182bff664d1f25009813f456c3ed12.js?body=1" defer></script>
```

</details>

--- 

What I'd suggest doing here is just dropping the defer attribute from https://github.com/alphagov/licence-finder/blob/584205a8812d45778e6f3907db8bc818de093a17/app/views/layouts/application.html.erb#L8 and moving that javavascript tag to the bottom of the HTML. It strikes me as unusual that this app has used `defer` compared to other GOV.UK apps, and given this app doesn't get a lot of love, it seems best to remove unconventional aspects. Then we can import jQuery the conventional way.

The other thing I'd suggest is install jQuery via a package manager - (as https://github.com/alphagov/govuk_publishing_components/blob/5f78cdb3f5d7c73ebd4337b664887c5341d511a4/package.json#L32) this app seems to be one of the only ones without a package.json currently and imagine a lightweight one can be added pretty easily and will mean we can treat jQuery as a more formal dependency here.

Are there any concerns that we have for this app and static bundling jQuery (aside from the quantity of JS)? Would we plan to ship this while static still provided jQuery or have an overlap? I'm guessing it's not a problem as long as jQuery versions match and there aren't extensions involved but seems a little fragile potentially.

We could also see if @edwardkerry would be interested in looking into the slimmer bug

**Comment by andysellick** [comment]
@kevindew thanks for looking into this, really appreciate your insight. Yes, I was falling foul of exactly the problem you discovered - when I tried to add `jquery.min.js` directly into `application.js` the output in the src was something like:

```
<script src="jquery.min.js" defer=true/>
<script src="application.js" defer=true/>
```

And since both scripts were deferred, application was invariably loading first and failing to find jQuery and erroring.

Have redone this approach based on your suggestions - removed the defer, moved the script to the foot of the template, added a package.json and included the jquery through application.js (I'll update the PR description shortly).

With regards to deployment, yes it is a bit thorny. I wouldn't want to have two jQuerys running at once but I'll check to see what effect that would have. Ideally we'd do a simultaneous deploy and try to minimise any overlap, but that's a few steps away.

**Comment by andysellick** [comment]
Update: just tried this with another jQuery still in static/the gem and it seems to run happily with two copies at once. Obviously we wouldn't want a situation like this live for very long (with the increase in asset size) but it means we can do a safe switchover.

**Comment by kevindew** [comment]
Great stuff, this all looks good to me now. Shout whenever you're ready to merge for when you'd like a ✅

**Comment by andysellick** [comment]
One sudden thought about this - if I'm introducing a `package.json` in this PR, does something need to be switched on in the deployment pipeline to make this work? Or will it detect this file and apply it accordingly?

**Comment by kevindew** [comment]
> One sudden thought about this - if I'm introducing a `package.json` in this PR, does something need to be switched on in the deployment pipeline to make this work? Or will it detect this file and apply it accordingly?

It'll happen automatically, as far as I understand because `rails assets:precompile` will run yarn install.

**Review by kevindew — APPROVED** [review]

**Pull request merged**
