### PR TITLE
Allow Elasticsearch URI

### PR DESCRIPTION
**Pull request by surminus**

### CODE REVIEW

**Comment by cbaines** [comment]
I think this won't work, as the configuration file is interpreted as YAML [1].

1: https://github.com/alphagov/licence-finder/blob/master/lib/search.rb#L8

You could change this to make it work though, I'm not quite sure what you'd write exactly, but this blog post has an example [2].

2: http://urgetopunt.com/2009/09/12/yaml-config-with-erb.html

**Comment by surminus** [comment]
Thanks @cbaines, I've pushed an update which is a slightly different approach. What do you think? I'll try to add some tests for this.

**Comment by cbaines** [comment]
> Thanks @cbaines, I've pushed an update which is a slightly different approach. What do you think? I'll try to add some tests for this.

Personally, I prefer your original approach. It's a bit more consistent with the configuration of other GOV.UK apps (which for better or worse, also use ERB/YAML), and is also more expressive, as you can set the Elasticsearch URI just by using the configuration file.

I've tested this snippet locally, and I think its all that is required to make the config you had originally work, which would go here [1]: 

```ruby
    client_config = HashWithIndifferentAccess.new(
      YAML.load(ERB.new(File.read(config_path)).result)
    )
```

1: https://github.com/alphagov/licence-finder/blob/master/lib/search.rb#L8

**Comment by surminus** [comment]
Great, I've updated my approach again :)

**Comment by surminus** [comment]
If you're happy with the code then that's fine with me, as long as I don't break anything! Thanks for your help.

**Pull request merged**
